sudo: required

language: c
sudo: required
dist: trusty

services:
  - docker

install:
  - sudo apt-get install docker.io
script:
  - docker run --privileged -i -t -v `pwd`/scripts:/root/scripts muvarov/lege-ci  /root/scripts/build.sh

after_success:
  - echo "Test Success"
